@startuml
skinparam defaultFontName Arial
box "Application" #FFFFFF
participant a as "main.c"
participant ah as "Application support\nmodules"
end box
participant c as "Mesh stack"
participant s as "Generic OnOff client"
box
participant core as "Mesh core modules"
end box

note over a: init_params defines UUID, core params\n and event callbacks
... Initialize ...
a -> ah: ble_stack_init()
a -> ah: gap_params_init()
a -> ah: conn_params_init()
a -> c: mesh_stack_init(...)
c -> core: Initialize: Mesh and Foundation models
... ...
a -> s: generic_onoff_client_init(...) x 2
... Start ...
a -> c: mesh_stack_start()
note over c: Start dynamic behavior


alt
    ... Provisioned node ...
    a <- s: onoff_status_cb(...)
    a <- s: ack_transaction_status_cb(...)
    a <- s: periodic_publish_cb(...)
    a -> s: generic_onoff_client_set/set_unack(...)
else
    ... Unprovisioned device ...
    a -> ah: mesh_provisionee_prov_start(...)
    group Initialize provisionee
    note over ah: Define OOB capabilities
    ah -> core: Start unprovisioned device beacon
    ah -> core: Listen for provisioning invite
    end
    ... Wait for provisioning to complete ...
    core -> ah: Provisioning Events
    ah -> a: provisioning_complete_cb()
    a -> ah: gap_params_init()
    a -> ah: conn_params_init()
end

@enduml
